export enum Tags {
    WMC = 'WMC',
    POSE = 'POSE',
    SYP = 'SYP',
    TYPESCRIPT = 'TYPESCRIPT',
    JAVA = 'JAVA',
    CSHARP = 'CSHARP',
    EASY = 'EASY',
    MEDIUM = 'MEDIUM',
    HARD = 'HARD',
    JAHRGANG1 = 'JAHRGANG1',
    JAHRGANG2 = 'JAHRGANG2',
    JAHRGANG3 = 'JAHRGANG3',
    JAHRGANG4 = 'JAHRGANG4',
    JAHRGANG5 = 'JAHRGANG5',
}

