version: '3.8'

networks:
  custom-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24

volumes:
  leocode-mysql-data:

services:
  traefik:
    image: traefik:v2.11
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./certs:/letsencrypt
    networks:
      - custom-net

  leocode-my-sql:
    image: mysql:5.7
    container_name: leocode-mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: leocode
      MYSQL_USER: leocodeAdmin
      MYSQL_PASSWORD: password
    volumes:
      - leocode-mysql-data:/var/lib/mysql
    networks:
      - custom-net

  leocode-adminer:
    image: adminer
    container_name: leocode-adminer
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.leocode-adminer.rule=Host(`leocode.htl-leonding.ac.at`) && PathPrefix(`/adminer`)"
      - "traefik.http.services.leocode-adminer.loadbalancer.server.port=8080"
    depends_on:
      - leocode-my-sql
    networks:
      - custom-net

  leocode-api:
    image: florianhagmair06/leocode-db:latest
    container_name: leocode-api
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: 'Development'
    depends_on:
      - leocode-my-sql
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.leocode-api.rule=Host(`leocode.htl-leonding.ac.at`) && PathPrefix(`/db`)"
      - "traefik.http.services.leocode-api.loadbalancer.server.port=5015"
    networks:
      - custom-net

  leocode-frontend:
    image: florianhagmair06/leocode-frontend:latest
    container_name: leocode-frontend
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.leocode-frontend.rule=Host(`leocode.htl-leonding.ac.at`) && PathPrefix(`/`)"
      - "traefik.http.services.leocode-frontend.loadbalancer.server.port=80"
    networks:
      - custom-net

  keycloak-api:
    image: florianhagmair06/keycloak:latest
    container_name: keycloak-api
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak-api.rule=Host(`leocode.htl-leonding.ac.at`) && PathPrefix(`/keycloak`)"
      - "traefik.http.services.keycloak-api.loadbalancer.server.port=5001"
    networks:
      - custom-net
    extra_hosts:
      - "auth.htl-leonding.ac.at:10.191.112.13"

  leocode-backend:
    image: florianhagmair06/leocode-backend:latest
    container_name: leocode-backend
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.leocode-backend.rule=Host(`leocode.htl-leonding.ac.at`) && PathPrefix(`/backend`)"
      - "traefik.http.services.leocode-backend.loadbalancer.server.port=5080"
    networks:
      - custom-net

  leocode-csharp-runner:
    image: florianhagmair06/leocode-csharp-runner:latest
    container_name: leocode-csharp-runner
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.leocode-csharp-runner.rule=Host(`leocode.htl-leonding.ac.at`) && PathPrefix(`/csharp-runner`)"
      - "traefik.http.services.leocode-csharp-runner.loadbalancer.server.port=5168"
    networks:
      - custom-net
    entrypoint: >
        /bin/sh -c "
        apt-get update &&
        apt-get install -y wget &&
        wget https://dot.net/v1/dotnet-install.sh &&
        chmod +x dotnet-install.sh &&
        ./dotnet-install.sh --channel 8.0 &&
        rm dotnet-install.sh &&
        export PATH=/root/.dotnet:$PATH &&
        mkdir -p /app/templates &&
        exec dotnet csharp-runner.dll"
