services:
  traefik:
    image: traefik:v2.11
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - 80:80
      - 443:443
      - 8080:8080
      - 8081:8081
      - 8082:8082
      - 8083:8083
      - 8084:8084
      - 8085:8085
      - 8086:8086
      - 8087:8087
    expose:
      - "8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./certs:/letsencrypt


  leocode-my-sql:
    image: mysql:5.7
    container_name: leocode-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: leocode
      MYSQL_USER: leocodeAdmin
      MYSQL_PASSWORD: password
    volumes:
     - leocode-mysql-data:/var/lib/mysql
     - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  
  leocode-adminer:
    image: adminer
    restart: always
    container_name: leocode-adminer
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.leocode-adminer.rule=Host(`leocode.htl-leonding.ac.at`) && PathPrefix(`/adminer`)"
      - "traefik.http.services.leocode-adminer.loadbalancer.server.port=8080"
    links:
      - leocode-my-sql
    depends_on:
      - leocode-my-sql

  leocode-api:
    restart: always
    container_name: leocode-api
    image: florianhagmair06/leocode-db
    depends_on:
      - leocode-my-sql
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:8080

  leocode-frontend:
    image: florianhagmair06/leocode-frontend
    container_name: leocode-frontend
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.leocode-frontend.rule=Host(`leocode.htl-leonding.ac.at`)&&PathPrefix(`/`)"
      - "traefik.http.services.leocode-frontend.loadbalancer.server.port=80"

  keycloak-api:
    image: florianhagmair06/keycloak
    container_name: keycloak-api
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak-api.rule=Host(`leocode.htl-leonding.ac.at`) && PathPrefix(`/keycloak`)"
      - "traefik.http.services.keycloak-api.loadbalancer.server.port=8081"

volumes:
  leocode-mysql-data: