services:
  traefik:
    image: traefik:v2.11
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - 80:80
      - 443:443
      - 8080:8080
      - 8081:8081
      - 8082:8082
      - 8083:8083
      - 8084:8084
      - 8085:8085
      - 8086:8086
      - 8087:8087
    expose:
      - "8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./certs:/letsencrypt

  leocode-seq:
    image: datalust/seq:latest
    container_name: leocode-seq
    volumes:
      - seq-data:/data          
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
    networks: 
      - leocode-network


  leocode-my-sql:
    image: mysql:5.7
    container_name: leocode-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: leocode
      MYSQL_USER: leocodeAdmin
      MYSQL_PASSWORD: password
    volumes:
      - leocode-data:/var/lib/mysql
  
  leocode-adminer:
    image: adminer
    restart: always
    container_name: leocode-adminer
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.leocode-adminer.rule=Host(leocode.htl-leonding.ac.at) && PathPrefix(/adminer)"
      - "traefik.http.services.leocode-adminer.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.adminer-strip-prefix.stripprefix.prefixes=/adminer"
      - "traefik.http.routers.leocode-adminer.middlewares=adminer-strip-prefix"
    networks:
      - leocode-network
    links:
      - my-sql

  leocode-api:
    restart: always
    container_name: leocode-api
    image: florianhagmair06/leocode-db
    depends_on:
      - leocode-my-sql
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:8080
    networks:
      - leocode-network

  networks:
    leocode-network:
      driver: bridge  
      external: false
      ipam:
        config:
          - subnet: 10.4.0.0/16
  
  leocode-frontend:
    image: florianhagmair06/leocode-frontend
    container_name: leocode-frontend
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.leocode-frontend.rule=Host(`leocode.htl-leonding.ac.at`)&&PathPrefix(`/`)"
      - "traefik.http.services.leocode-frontend.loadbalancer.server.port=80"
  
  volumes:
    seq-data:
    leocode-data: